---
version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: db_username
          MYSQL_DATABASE: db_app_test
          MYSQL_PASSWORD: db_password
          MYSQL_ROOT_PASSWORD: $
          GIT_COMMIT_DESC: git log --format=%B -n 1 $CIRCLE_SHA1
    steps:
      - checkout
      - restore_cache:
          name: Restore bundle cache
          keys:
            - app-{{ checksum "Gemfile.lock" }}

      - run: gem install bundler:2.1.4

      - run: bundle install --path vendor/bundle

      - save_cache:
          name: Save bundle cache
          key: app-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      - run: cp .env.example .env

      - run: bundle exec rails db:prepare

      - when:
          condition:
            not: [$CI_PULL_REQUEST, ""]
          steps:
            - run: echo $CIRCLE_PULL_REQUEST
            - run: echo $CIRCLE_JOB
            - run: echo $CIRCLE_USERNAME
            - run: echo $GIT_COMMIT_DESC
            - slack/notify:
                channel: localhost
                color: "#42e2f4"
                mentions: "UCFR3ALMC"
                message: This is a custom message notification
                webhook: $SLACK_WEBHOOK

workflows:
  version: 2
  build:
    jobs:
      - build
